package fr.guddy.joos.domain;

import org.assertj.core.api.AbstractAssert;

/**
 * {@link Repo} specific assertions - Generated by CustomAssertionGenerator.
 */
public class RepoAssert extends AbstractAssert<RepoAssert, Repo> {

  /**
   * Creates a new <code>{@link RepoAssert}</code> to make assertions on actual Repo.
   * @param actual the Repo we want to make assertions on.
   */
  public RepoAssert(Repo actual) {
    super(actual, RepoAssert.class);
  }

  /**
   * An entry point for RepoAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myRepo)</code> and get specific assertion with code completion.
   * @param actual the Repo we want to make assertions on.
   * @return a new <code>{@link RepoAssert}</code>
   */
  public static RepoAssert assertThat(Repo actual) {
    return new RepoAssert(actual);
  }

}
